Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: dynamo-elastic-beanstalk-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: ec2.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: my-elastic-beanstalk-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - dynamodb:*
            Resource: ["arn:aws:dynamodb:*:*:table/EmployeeTable"]